language: android

android:
  components:
    # Use the latest revision of Android Tools
    - tools
    - platform-tools

    # When changing build-tools or SDK version, change also in build.gradle!
    - build-tools-26.0.2
    - android-27

    - extra-android-m2repository

before_install:
# Avoid ./gradlew: Permission denied
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-27"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: "schnatterer-github"
    token:
      secure: "Cm08TtboV6+yr1hzUOLOFB40ClEqGvIDVaT1IPB0dj01BmlvTmRx7ZcOo4ef9MS4ZPXNin7BQbR3gPRkClMC5ejITgUy6dpd7ILvNxk4/AWSR7CTN9w30vNdHSli371XHfAK4xPudLqlT7+ybVlVU7q59DsB5x9zOO7jxX7dMdA1/JpojZU124VUVjptKWUxQkJBDXHnWWMhOTcOhOwQ5oHkE3BoN0kQved9TvnpXu2GqiPG/M6fhq/bvDiu+HHwfE5lJadeeFMruKtw9I9/QyXRJeCJHA3FO2hwVk0R1uMMcyf8CAoTu0bQjhSC2BZ0lb79EE67P6p6uXcIqY+mWdSwjkdH+wCk41Zi/UyC1cedWjyHURKqJEWo6hzaG7/23i/GR0PhY2oyF+jYb6qyVqRD1ECTHGcO/KWXsuvRo+dgpDBaOVR4RuXb2rum8cJnlIpDmMKX9HC/XvtYtcy4b61w9sxylvHwV3AWMGU6hMcyftgqGWCpNVeW1bb1bVQKgeULuij0lvSDdSa/8XzZMRr7SxuNPEYR6c3c266tbPFtTWRwnHeVmEbuVNvZnDnrLlB1cHkIBrB6pHBg+1GOhXMPtNNM6Xgf2+Bdex5Dr+F/HePJdXW1d1fDcwpwZIriuKRBwc74ckvgdlwljNCDJV63NN1B0S0NtNDEp8qA7pY="
    github_token:
      secure: "Ue5mjFxVzBde7JWA1KFc3UFBYiOfmmQBDXzc0iR0QyLPM2c/QqM7/dl7ziPV9s+Xx2eci/76kNV4oWlrT0frFkF7S9Bs061rBqB+ZGQSi9VdXSYqAVf9PDt3iDSooNw4bZVOcMwFWRG84Y7AL3bCwyVIYeg9b1sPKy7K1mrg9P3YXoMo9j7ogCqlbCqd4siwiSnZmIBQU0Y/FFGe9Yk8FssMuZdIv2tjxTGXjgqr0LTjFo8EkgJwpdReec3axQomd9sd4s+zzKzfAZ9AkPbxzI6HW88pYDJhQnNd+ZYxiMnicwxjYxkyNta+1POdBX1wT/fh/dSMFbKk12ZpMpetFW4p0i81xabW5f5zM/TmJj7QyWqDIawUYtaYrYnJ/Pi1Ndhs1wXrcuucr+KX+arH/0yyFeiYWJD1+FdvWr/Pvpr4n+qB/sGqRzjNxF4tD9jowxbxXRKBLyWwT70WNb22HuS6GnwY7TSI4yZ57KQGJg3koDl6/SZ8qJMmtXQnIS0ufCfno/R58AlVq53GHpE7vHKMR7ERLHsFyBWKtd/RAS3LAUG3V7pNC7OlRirB+v0a0XOLoBjTGKFXmAVlrvjoUzbAFFRFmJenhV/emwJEKrMAQ8uTEW4WUrikXlIBexKsi2VT4TqzngYjRqG0h4WpS5hjJOMneqF9y3v42yfE42U="
    branches:
      - master
      - develop
      - feature/*

script: ./gradlew clean build connectedCheck sonarqube --stacktrace
